name: user_management_system
description: User Management System with Flutter
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  # Add other dependencies as needed

dev_dependencies:
  flutter_test:
    sdk: flutter


 
environment:
  sdk: ">=2.17.0 <3.0.0"
